#!/bin/bash
# g++ -std=c++20 -g -O3 -ffast-math -I"$1/include" "$1/main.cpp" -o "$1/bin/$2"
mkdir -p build && cd build
cmake -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Debug ..
cmake --build .
./ejemplo_bitmth
cd ..
